Repository yunify/qingcloud-csi, pull requests merged in 2019-10, with the labels that each got.

#132 modify user guide
  docs/user-guide-zh.md
Labels: approved, kind/documentation, lgtm, size/S

#135 update readme for new release file
  README.md
  README_zh.md
Labels: approved, kind/documentation, lgtm

#137 update attach map
  Makefile
  deploy/disk/kubernetes/overlays/patch/kustomization.yaml
  deploy/disk/kubernetes/releases/qingcloud-csi-disk-v1.1.0-rc.3.yaml
  docs/user-guide-zh.md
  pkg/disk/driver/types.go
Labels: approved, kind/documentation, kind/feature, lgtm, size/XL

#139 support more volume and instance type
  README.md
  README_zh.md
  docs/user-guide-zh.md
  pkg/disk/driver/types.go
  pkg/disk/rpcserver/controllerserver_test.go
Labels: approved, kind/documentation, kind/feature, lgtm, size/L

#140 update changelog
  CHANGELOG.md
Labels: approved, kind/documentation, lgtm, size/XS

#143 update sc and add mutex
  Makefile
  cmd/disk/main.go
  deploy/disk/kubernetes/overlays/patch/controller-deploy.yaml
  deploy/disk/kubernetes/overlays/patch/kustomization.yaml
  deploy/disk/kubernetes/overlays/patch/node-ds.yaml
  deploy/disk/kubernetes/releases/qingcloud-csi-disk-v1.1.0-rc.4.yaml
  go.sum
  pkg/disk/driver/snapshotclass.go
  pkg/disk/driver/snapshotclass_test.go
  pkg/disk/driver/storageclass.go
  pkg/disk/driver/storageclass_test.go
  pkg/disk/driver/types.go
  pkg/disk/driver/types_test.go
  pkg/disk/rpcserver/controllerserver.go
  pkg/disk/rpcserver/nodeserver.go
Labels: approved, kind/feature, lgtm, size/XXL

#146 add identity server unittest
  go.mod
  go.sum
  pkg/cloud/mock/mock_cloud_manager.go
  pkg/cloud/mock/mock_storage_system.go
  pkg/cloud/mock/mock_storage_system_test.go
  pkg/common/rpcserver.go
  pkg/disk/driver/driver.go
  pkg/disk/rpcserver/controllerserver_test.go
  pkg/disk/rpcserver/identityserver.go
  pkg/disk/rpcserver/identityserver_test.go
  vendor/modules.txt
Labels: approved, kind/feature, lgtm, size/L

#149 Remove targetpath in node unpublish
  pkg/disk/rpcserver/nodeserver.go
Labels: approved, kind/feature, lgtm, size/M

#150 Update docs and add more resource on external attacher
  README.md
  README_zh.md
  deploy/disk/kubernetes/base/controller-deploy.yaml
  deploy/disk/kubernetes/releases/qingcloud-csi-disk-v1.1.0-rc.4.yaml
  docs/developer-guide-zh.md
  docs/user-guide-zh.md
Labels: approved, kind/documentation, lgtm, size/L
